[tool.poetry]
name = "testate"
version = "0.1.0"
description = ""
authors = ["Marco Bakera <marco@bakera.de>"]

[tool.poetry.dependencies]
python = "^3.7"
Flask = "^2.0.2"
gunicorn = "^20.1.0"
Flask-SQLAlchemy = "^2.5.1"
python-dotenv = "^0.19.2"
Flask-Login = "^0.5.0"
GitPython = "^3.1.27"
openpyxl = "^3.0.9"

[tool.poetry.dev-dependencies]
pylint = "^2.12.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
